#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above requirements

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
