#!/usr/bin/env bash
# configuring a new server to install haproxy and load balance between 2 servers

sudo apt-get -y update

apt-get -y install haproxy

echo -e "\nfrontend front_http\n\tbind *:80\n\tmode http\n\n\tdefault_backend back_http" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend back_http\n\tbalance roundrobin\n\tserver 120457-web-01 54.234.126.199:80 check\n\tserver 120457-web-02 54.237.90.167:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
