#!/usr/bin/env bash
#using for loop to print

NUM="1"

while [ "$NUM" -lt "11" ]
do
    
    if [ "$NUM" -eq "9" ]; then
    echo "Best School"
    echo "Hi"
    else
    echo "Best School"
    fi
    NUM="$((NUM + "1"))"
done
