#!/usr/bin/env bash
#using for loop to print

NUM="11"

while [ "$NUM" -gt "0"]
do
    
    if [ "$i" -eq "9" ]; then
    echo "Best School"
    echo "Hi"
    else
    echo "Best School"
    fi
    NUM="$((NUM - 1))"
done
