#!/usr/bin/env bash
#using while loop and if statements

NUM="1"
while [ "$NUM" -lt "11" ]; do
    if [ "$NUM" -eq "4" ]; then
        echo "bad luck"
    elif [ "$NUM" -eq "8" ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    NUM=$(( NUM + 1))
done
