#!/usr/bin/env bash
#using loop to print time

HOUR="0"
while [ "$HOUR" -lt "12" ]; do
    echo "HOUR: $HOUR"
    MINUTE="0"
    while [ "$MINUTE" -lt "60" ]; do
        echo "$MINUTE"
        MINUTE=$(( MINUTE + 1))
    done
    HOUR=$(( HOUR + 1))
done
